### ISSUE TITLE
[Bug] Crash when exiting a world while in a party

### ISSUE THREAD

**Issue by LolJohn11** [matthe815s-projects/mmo-parties#44]
When quitting a single-player world while being inside a party, the game produces a crash on the "saving world" screen. I don't know whether this bug occurs in multiplayer since I haven't tested it that way yet.
I understand that since there is no real reason for anyone to use the party system while in singleplayer, this situation is extremely unlikely 
to happen and thus not really a game-breaking bug, but I still think it's worth reporting.

Here's a link to the [crash log](https://crashy.net/ClnbeCOl8s9ysReZVqCM).

**Comment by matthe815** [comment]
Thank you for the report. I will look into it.
