### ISSUE TITLE
Crashing on 1.19.2

### ISSUE THREAD

**Issue by YassaaaTU** [matthe815s-projects/mmo-parties#59]
This crash report happend when I pressed P (crashes on random)
https://mclo.gs/hqYvtBW

And this Crash report is when I typed "/party gui"
https://mclo.gs/sIjAsgL

**Comment by Sazuzaki** [comment]
Can confirm, hope this gets fixed

**Comment by matthe815** [comment]
I am investigating this issue. It will get fixed soon.

**Comment by matthe815** [comment]
I believe i have a fix for it
