### ISSUE TITLE
Delete system.out.printlns

### ISSUE THREAD

**Issue by Kitoglav** [matthe815s-projects/mmo-parties#68]
Hello. Can you please delete all your System.out.println calls in networking? It spams a lot of garbage lines in logs and does mod uncomfortable to play (MultiMC crashes client cuz of large log file)
For example: https://github.com/matthe815s-projects/mmo-parties/blob/1.19-release/src/main/java/deathtags/networking/MessageSendMemberData.java

"Wrote packet"
"Packet"

**Comment by matthe815** [comment]
It seems like something I've overlooked in the latest releases, my apologies. I shall get it fixed.
