### ISSUE TITLE
Mod does not load on 1.20.1

### ISSUE THREAD

**Issue by johalun** [matthe815s-projects/mmo-parties#70]
Does not seem to support 1.20.1. Forge version 1.20.1-47.2.32. 

Log

```
-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
-- MOD mmoparties --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/network/ChannelBuilder
		at deathtags.core.MMOParties.<clinit>(MMOParties.java:58) ~[mmoparties-2.4.4.jar%23470!/:2.4.3] {re:classloading}
```

**Comment by matthe815** [comment]
Thank you for the report. It appears 1.20.1 is the one version with wildly different networking APIs compared to 1.20.2

**Comment by P4YN-Ki** [comment]
Can confirm I'm also getting this error just trying to load into the game. Minecraft 1.20.1 and Forge 47.3.1 - I've attached a Screenshot though I don't think it'll be much use. My Error log literally says the same as OP, so there's nothing really to add other then I'm also experiencing this.
![image](https://github.com/matthe815s-projects/mmo-parties/assets/38091393/6180a70e-d7cb-4f65-bcb0-dc42767d6ed0)
